# 1.퍼셉트론

### 1-1.파이썬으로 구현한 퍼셉트론-1

In [1]:
import numpy as np

In [2]:
X = np.array([1,0,1])
print(X)

[1 0 1]


In [5]:
W = np.array([
    -0.5,
    1.0,
    1.0
])
print(W)

[-0.5  1.   1. ]


In [6]:
y = sum(X*W)
y

0.5

### 1-2.파이썬으로 구현한 퍼셉트론-2

In [7]:
import numpy as np

In [8]:
X = np.array([
    [1,0,0],
    [1,0,1],
    [1,1,0],
    [1,1,1]
])
print(X)

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [9]:
W = np.array([
    -0.5,
    1.0,
    1.0
])
print(W)

[-0.5  1.   1. ]


In [11]:
y = np.sum(X*W, axis=1)
y

array([-0.5,  0.5,  0.5,  1.5])

### 1-3. 퍼셉트론을 이용해 AND 논리 구하기-활성화 함수 추가

In [12]:
import numpy as np

In [13]:
def ANDperceptron(x1, x2):
    w1, w2, theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1

In [14]:
inputData = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])
print(inputData)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [15]:
print("+++ AND Perceptron +++")
for xs in inputData:
    print(str(xs) + ">>>" + str(ANDperceptron(xs[0], xs[1])))

+++ AND Perceptron +++
[0 0]>>>0
[0 1]>>>0
[1 0]>>>0
[1 1]>>>1


### 1-4. 퍼셉트론을 이용해 AND 논리 구하기-활성화 함수 추가+편향 도입하기

In [16]:
import numpy as np

In [17]:
def ANDperceptron(x1, x2):
    x = np.array([x1,x2])
    w = np.array([0.5, 0.5])
    b = -0.7 # 새로 추가된 편향
    tmp = np.sum(x*w) + b # 완성된 NN
    if tmp <= 0:
        return 0
    elif tmp > 0:
        return 1    

In [18]:
inputData = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])
print(inputData)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [19]:
for xs in inputData:
    print(str(xs) + ">>>" + str(ANDperceptron(xs[0], xs[1])))

[0 0]>>>0
[0 1]>>>0
[1 0]>>>0
[1 1]>>>1


### 1-5. 퍼셉트론을 이용해 AND 논리 구하기-마지막 학습 시키기

In [20]:
import numpy as np

In [21]:
# 1.AND 데이터 셋 만들어 주기

X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])
y = np.array([0,0,0,1]) # 학습을 시키고자 할 경우, 정답 데이터(라벨)이 필요합니다.
print("입력 데이터 셋 >>>", X)
print("정답 데이터 셋 >>>", y)

입력 데이터 셋 >>> [[0 0]
 [0 1]
 [1 0]
 [1 1]]
정답 데이터 셋 >>> [0 0 0 1]


In [22]:
# 2.가중치 초기화

w = np.zeros(1 + X.shape[1])
print(w)

[0. 0. 0.]


In [23]:
# 3.최초 분류

input_signal = np.dot(X, w[1:]) + w[0]

In [24]:
def out_put(X):
    return np.where(X >= 0.0, 1, 0)

In [25]:
y_hat = out_put(input_signal)
print(y_hat)

[1 1 1 1]


In [28]:
# 4. 학습을 시키겠습니다.

errors = [] # y-y_hat 오차
epoch = 100 # 반복 학습 시 가장 중요한 요소

for time in range(0, epoch):
    print("{0}번째 반복입니다".format(time))
    eta = 0.01 # 편향 값
    idx = 0
    for xi, target in zip(X,y):
        updated_w = eta * (target - y_hat[idx]) #가중치 업데이트 공식
        w[1:] += updated_w * xi
        w[0] += updated_w
        idx +=1
    input_signal = np.dot(X, w[1:]) + w[0] # ANN 가설 식 
    y_hat = out_put(input_signal) # 가설 식을 이용한 추론 값 곧, 예측값
    errors.append(((y-y_hat).sum()) / 100)
    print(((y-y_hat).sum()) / 100)
    if((y-y_hat).sum()) / 100 == 0:
        break
        
print(y_hat)     
    

0번째 반복입니다
0.01
1번째 반복입니다
-0.02
2번째 반복입니다
0.01
3번째 반복입니다
0.0
[0 0 0 1]


# 2. 딥러닝

## 2-1. 딥러닝 도구

#### 2-1-1. Tensorflow

In [30]:
pip install chardet

   ---------------------------------------- 0.0/199.4 kB ? eta -:--:--
   ------ --------------------------------- 30.7/199.4 kB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 199.4/199.4 kB 3.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [1]:
import tensorflow as tf

##### 2-1-1-1 텐서 1.0

In [3]:
import tensorflow as tf
with tf.compat.v1.Session() as sess:
    helloworld = tf.constant("Hello World!!!")
    print(sess.run(helloworld))

b'Hello World!!!'


##### 2-1-1-2 텐서 2.0

In [4]:
import tensorflow as tf
helloworld = tf.constant("Hello World!!!")
tf.print(helloworld)

Hello World!!!


#### 2-2-1. Tensorflow 를 이용한 논리게이트 문제풀이

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
import numpy as np

In [3]:
xy = np.loadtxt("train.txt")
x_data = xy[0:-1]
y_data = xy[-1]

print("x_data >>>",x_data)
print("y_data >>>", y_data)

x_data >>> [[0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 1.]]
y_data >>> [1. 1. 0.]


In [4]:
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [5]:
W = tf.Variable(tf.random_uniform([1, len(x_data)], 1.0, 1.0))

In [6]:
h = tf.matmul(W, X)
hypothesis = tf.div(1., 1.+tf.exp(-h))

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.


In [7]:
# 훈련 비용

cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))

In [8]:
learning_rate = tf.Variable(0.01)
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(cost)

init =  tf.global_variables_initializer()

In [9]:
# 훈련

with tf.Session() as sess:
    sess.run(init)

    for step in range(5001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 500 == 0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W))

    #학습 모델
    correct_prediction = tf.equal(tf.floor(hypothesis+0.5), Y)

    #정확도 계산
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))

    print(sess.run(
        [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy],
        feed_dict={X:x_data, Y:y_data}
    ))

    print("정확도 : ", accuracy.eval({X:x_data, Y:y_data}))

0 0.9169857 [[1.        0.9979605 0.9979605]]
500 0.71802014 [[1.         0.31737986 0.31737986]]
1000 0.69525355 [[1.        0.0918394 0.0918394]]
1500 0.6933201 [[1.        0.0262968 0.0262968]]
2000 0.6931613 [[1.         0.00752298 0.00752298]]
2500 0.6931484 [[1.         0.00215201 0.00215201]]
3000 0.69314724 [[1.0000000e+00 6.1559887e-04 6.1559887e-04]]
3500 0.6931472 [[1.0000000e+00 1.7609312e-04 1.7609312e-04]]
4000 0.6931472 [[1.0000000e+00 5.0383616e-05 5.0383616e-05]]
4500 0.6931472 [[1.0000000e+00 1.4399263e-05 1.4399263e-05]]
5000 0.6931472 [[1.000000e+00 4.106438e-06 4.106438e-06]]
[array([[0.500001 , 0.500001 , 0.5000021]], dtype=float32), array([[1., 1., 1.]], dtype=float32), array([[ True,  True, False]]), 0.6666667]
정확도 :  0.6666667
