## Set Up

In [ ]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family'] = 'Malgun Gothic' # Windows
# matplotlib.rcParams['font.family'] = 'AppleGothic' # Mac
matplotlib.rcParams['font.size'] = 15 # 글자 크기
matplotlib.rcParams['axes.unicode_minus'] = False # 한글 폰트 사용 시, 마이너스 글자가 깨지는 현상을 해결

##  XOR 문제 해결

In [ ]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

import numpy as np

xy = np.loadtxt('train.txt')
print(xy)

Instructions for updating:
non-resource variables are not supported in the long term
[[0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


In [ ]:
x_data = xy[:,:-1]
y_data = xy[:,-1]

print(x_data)
print("*****")
print(y_data)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
*****
[0. 1. 1. 0.]


In [ ]:
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None])

W = tf.Variable(tf.random_uniform([2, 1], -1.0, 1.0))

In [ ]:
# Our hypothesis
h = tf.matmul(X, W)
hypothesis = tf.div(1., 1.+tf.exp(-h))

# Cross entropy cost function
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))

learning_rate = tf.Variable(0.01)
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(cost)


init = tf.global_variables_initializer()

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.


In [ ]:
with tf.Session() as sess:
    sess.run(init)
    for step in range(5001):
        sess.run(train, feed_dict={X:x_data, Y:y_data })
        if step % 500 == 0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W))

# Test model
    correct_prediction = tf.equal(tf.floor(hypothesis + 0.5), tf.reshape(Y, [-1, 1]))


# Calculate Accuracy
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    h_val, p_val, c_val, a_val = sess.run([hypothesis, tf.floor(hypothesis + 0.5), correct_prediction, accuracy], feed_dict={X: x_data, Y: y_data})
    print("각 입력 인스턴스에 대한 모델이 예측한 확률:\n", h_val, "\nPredicted:\n", p_val, "\nCorrect:\n", c_val, "\nAccuracy:", a_val)

0 0.7299391 [[-0.8265155 ]
 [ 0.71473473]]
500 0.7132854 [[-0.5927075]
 [ 0.5475155]]
1000 0.7040893 [[-0.42866048]
 [ 0.4106518 ]]
1500 0.6990567 [[-0.3115958]
 [ 0.3044785]]
2000 0.69632614 [[-0.2271553 ]
 [ 0.22435547]]
2500 0.6948533 [[-0.16586208]
 [ 0.1647634 ]]
3000 0.6940617 [[-0.12121289]
 [ 0.12078233]]
3500 0.69363695 [[-0.08862452]
 [ 0.08845592]]
4000 0.69340944 [[-0.06481393]
 [ 0.06474795]]
4500 0.69328755 [[-0.04740692]
 [ 0.0473811 ]]
5000 0.6932223 [[-0.03467734]
 [ 0.03466725]]
각 입력 인스턴스에 대한 모델이 예측한 확률:
 [[0.5       ]
 [0.5086659 ]
 [0.49133152]
 [0.4999975 ]] 
Predicted:
 [[1.]
 [1.]
 [0.]
 [0.]] 
Correct:
 [[False]
 [ True]
 [False]
 [ True]] 
Accuracy: 0.5
